server:
  port: 8080
spring:
  redis:
    host: 192.168.1.21
    port: 6379
   # password:
    jedis:
      pool:
         max-active: 8
         max-wait: -1
         max-idle: 8
         min-idle: 0
    timeout: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/huangdemo?characterEncoding=utf-8&&useSSL=false&allowMultiQueries=true
    name: localhost_3306
  cache:
     ehcache:
       config: classpath:cache/ehcache.xml
     type: ehcache

mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    org:
      mybatis: debug

